JdeRobot/RoboticsAcademy

- src/ardrone_cat_mouse/cat_drone/CMakeLists.txt
- src/ardrone_cat_mouse/cat_drone/drone_sensors.cpp
- src/ardrone_cat_mouse/mouse_drone/CMakeLists.txt
Fast script to deploy https://gist.github.com/fqez/42dbb5faea154e7afe79
> [issue #14] fixed compilation of: cat_drone and mouse_drone

- src/follow_line/README.md
- src/follow_line/run_it.sh
Add missing instructions (spanish) for follow_line
> Follow line instructions

- src/obstacle_avoidance/gazebo/simpleCircuitObstacles.world
issue #52 fix half-broken gazebo world
bugs:
* noneditable
* broken colliders
> issue #52 fix half-broken gazebo world

- .gitignore
Copied [python.gitignore](https://github.com/github/gitignore/blob/master/Python.gitignore)
> [issue #86] Added python gitignore

- src/global_navigation/sensors/sensor.py
solved bug with pose3d in global navigation (#119)
> [issue #119] solved bug with pose3d in global navigation

- src/color_filter/README.md
- src/color_filter/color_tuner_conf.cfg
- src/color_filter/color_tuner_conf.yml
Updated execution instructions in README.md
Changed colorTuner Tool's configuration file to .yml
Deleted .cfg colorTuner's file
> Tune up "color_filter" Practice

- src/color_filter/color_tuner_conf.cfg
- src/follow_turtlebot/README.md
- src/follow_turtlebot/color_tuner_conf.cfg
- src/follow_turtlebot/color_tuner_conf.yml
- src/follow_turtlebot/kobukiViewer.yml
- src/follow_turtlebot/turtlebot.cfg
Several changes made for follow_turtlebot excersise:
- Updated README.md
- Changed kobukiViewer's configuration file to .yml, as expected by the tool (turtlebot.cfg->kobukiViewer.yml)
- Changed colorTuner's configuration file to .yml, as expected by the tool, and modified in order to take images from Drone's camera (color_tuner_conf.cfg->color_tuner_conf.yml)
> Tune up academy excersises

- src/autopark/README.md
- src/drone_cat_mouse/README.md
- src/global_navigation/README.md
- src/vacuum_cleaner/README.md
The autopark and global_navigation READMEs have been translate into english. These updates of the READMEs fix the #132 and #133 issues
Also update the drone_cat_mouse and vacuum_cleaner READMEs. These updates fix the #139 issue
> Fix #123 and #133 issue: Translation of autopark and global navigation READMEs

- src/visual_lander/README.md
This Pull-request fix the #166 issue.
> Update README.md for Visual_lander practice

- src/3d_reconstruction/gui/form.py
- src/Stop_Practice/gui/form.py
- src/autopark/gui/form.py
- src/color_filter/gui/ui_gui.py
- src/drone_cat_mouse/cat_py/gui/ui_gui.py
- src/follow_line/gui/form.py
- src/follow_road/gui/ui_gui.py
- src/follow_turtlebot/gui/ui_gui.py
- src/global_navigation/gui/ui_gui.py
- src/labyrinth_escape/gui/ui_gui.py
- src/obstacle_avoidance/gui/form.py
- src/position_control/gui/ui_gui.py
- src/rescue_people/gui/ui_gui.py
- src/vacuum_cleaner/gui/form.py
- src/vacuum_practice/gui/form.py
- src/visual_lander/gui/ui_gui.py
Solves #170 
Due to the STOP button on the GUI of all exercises does not stop the movement (it just stops the execution of the student's code), I've been told to change the text content in the buttons.
> SOLVE  #170 - GUI: STOP->STOP CODE and PLAY->PLAY CODE

- src/follow_turtlebot/MyAlgorithm.py
- src/follow_turtlebot/README.md
This pull-request fixed the #178 issue.
> Updated Follow_turtlebot practice README.md

- src/follow_line/gui/GUI.py
- src/follow_turtlebot/gui/GUI.py
- src/vacuum_cleaner/gui/GUI.py
- src/vacuum_practice/gui/GUI.py
- src/visual_lander/gui/GUI.py
This pull-request fixes the #192 and #191 issues.
> Fixed the Toggle Button colours. (#191 and #192 issue).

- exercises/vacuum_cleaner/referee.py
- exercises/vacuum_slam/referee.py
Solves #231 
Changed Referees of Vacuum_Cleaner and Vacuum_Slam practices to show a more precise percentage of the cleared area.
> [Solve #231] More precise percentage of the cleared area in referee

- exercises/follow_line/MyAlgorithm.py
- exercises/follow_line/README.md
README.md has been updated with correct launching instructions.
Closes#286
> Updated README.md for follow_line 

- exercises/follow_line/MyAlgorithm.py
- exercises/follow_line/README.md
Solve https://github.com/JdeRobot/RoboticsAcademy/issues/303 and https://github.com/JdeRobot/RoboticsAcademy/issues/294 issues
> Update API commands in Readme and MyAlgorithm

- docs/_portfolio/follow_line.md
Fixed the URL of assets that were not loading.
> Minor fixes to view images

- docs/_portfolio/follow_line.md
- exercises/follow_line/MyAlgorithm.py
Solves #363 
removed the instruction **source /opt/jderobot/share/jderobot/gazebo/gazebo-setup.sh** as it was showing no file or directory present and improves the documentation.
Also removed the Jderobot module as this dependency is not required in this exercise.
> removed unneccessary instruction for exercise Follow_line

- exercises/vacuum_cleaner/README.md
This solves  the issue #373
I had updated the readme for vacuum_exercise which includes links to theory and hints and instruction to enable kobuki_msgs.
> updated readme

- docs/_pages/installation.md
Fix issue #381
change the kinteic to melodic
> ROSinstallation

- docs/_config.yml
- docs/_data/navigation.yml
- docs/_pages/about.md
- docs/_pages/exercises/MobileRobots/MobileRobots.md
- docs/_pages/exercises/MobileRobots/follow_line.md
- docs/_pages/exercises/exercises.md
- docs/_site/404.html
- docs/_site/index.html
> first prototype of new organization instead of a single level portfolio

- docs/_data/navigation.yml
- docs/_pages/home.md
> New URLs based on academy.jderobot.org

- docs/_pages/exercises.md
- docs/_pages/exercises/Drones/drone_hangar.md
- docs/_pages/exercises/Drones/drones_section.md
- docs/_pages/exercises/Drones/labyrinth_escape.md
- docs/_pages/exercises/Drones/position_control.md
- docs/_pages/exercises/Drones/rescue_people.md
Exercises added: labyrinth_escape, position_control, rescue_people, drone_hangar. 
Working on issue #418.
> Added 4 new drones exercises

- docs/_pages/exercises/Drones/drone_hangar.md
- docs/_pages/home.md
> Fixs #427 - link errors

- README.md
This info is shown in repository wiki section. Fix #432
> Link to contribute section fixed

- docs/_pages/exercises/Drones/position_control.md
This drone exercise has been solved and updated with new relevant information (#418)
> Position control exercise updated

- docs/_pages/exercises/AutonomousCars/global_navigation.md
Regarding issue #461 
Collections of images are clubbed into galleries.
> Updated Gallery

- exercises/chrono/MyAlgorithm.py
> indentation error solved

- docs/_pages/exercises/AutonomousCars/follow_line.md
- docs/_pages/exercises/AutonomousCars/global_navigation.md
- docs/_pages/exercises/AutonomousCars/obstacle_avoidance.md
- docs/_pages/exercises/Drones/drone_cat_mouse.md
- docs/_pages/exercises/Drones/drone_hangar.md
- docs/_pages/exercises/Drones/follow_road.md
- docs/_pages/exercises/Drones/follow_turtlebot.md
- docs/_pages/exercises/Drones/labyrinth_escape.md
- docs/_pages/exercises/Drones/position_control.md
- docs/_pages/exercises/Drones/rescue_people.md
- docs/_pages/exercises/Drones/visual_lander.md
- docs/_pages/exercises/MobileRobots/amazon_warehouse.md
- docs/_pages/exercises/MobileRobots/vacuum_cleaner.md
- docs/_pages/exercises/MobileRobots/vacuum_cleaner_loc.md
This is in reference to issue #476 
The section for installation instructions has been added to all the exercise webpages
> Update Installation Instructions

- README.md
Solves https://github.com/JdeRobot/RoboticsAcademy/issues/489
> Update contribute link

- docs/_pages/installation.md
> Adding environment setup in the installation page

- docs/_pages/installation.md
> Adding environment setup instructions for both base and assets

- docs/_pages/exercises/AutonomousCars/follow_line.md
- docs/_pages/exercises/AutonomousCars/global_navigation.md
- docs/_pages/exercises/AutonomousCars/obstacle_avoidance.md
- docs/_pages/exercises/Drones/drone_cat_mouse.md
- docs/_pages/exercises/Drones/drone_hangar.md
- docs/_pages/exercises/Drones/follow_road.md
- docs/_pages/exercises/Drones/follow_turtlebot.md
- docs/_pages/exercises/Drones/labyrinth_escape.md
- docs/_pages/exercises/Drones/position_control.md
- docs/_pages/exercises/Drones/rescue_people.md
- docs/_pages/exercises/Drones/visual_lander.md
- docs/_pages/exercises/MobileRobots/amazon_warehouse.md
- docs/_pages/exercises/MobileRobots/vacuum_cleaner.md
- docs/_pages/exercises/MobileRobots/vacuum_cleaner_loc.md
- docs/_pages/installation.md
> Moving sources from exercises to generic infrastructure

- docs/_pages/exercises/Drones/follow_turtlebot.md
- docs/_pages/exercises/Drones/visual_lander.md
> Updating specific instructions at drones exercises

- exercises/obstacle_avoidance/gui/GUI.py
Credits for this solution to @dhrodao. Now the visualization is coherent with the robot relative coordinate system: X+ ahead of the robot, Y+ to the left of the robot.
It solves #505
> #505 solution

- exercises/3d_reconstruction/MyAlgorithm.py
- exercises/3d_reconstruction/gui/form.py
- exercises/3d_reconstruction/gui/widgets/graphicWidget.py
- exercises/3d_reconstruction/interfaces/point.py
This is in reference to issue #510 
Further optimizations added for efficient rendering of points in OpenGL
> Optimizations

- docs/_pages/exercises/ComputerVision/3d_reconstruction.md
This is in reference to issue #518 
The updated reference solution link is added
> Update Video Link

- exercises/color_filter/Camera/cameraSegment.py
- exercises/color_filter/gui/ui_gui.py
This is in reference to #523 
- In this pull request, I've removed the small redundant window in the GUI. 
- Removed the redundant part of the ICE code.
_(the live video stream window plays the stream even after the code has been stopped)_
> Clean GUI for Color_filter exercise

- docs/_pages/exercises/Drones/drone_cat_mouse.md
> Added information for launching autonomous mice

- docs/_pages/exercises/Drones/drone_cat_mouse.md
> Added xmlstarlet dependency

- exercises/follow_line/web-template/launch/f1_circuit.world
- exercises/follow_line/web-template/launch/simple_line_follower_ros.launch
This is in reference to issue #562 
The world and launch files are added in the web-templates version of follow line
> Add world and launch files for Follow Line

- exercises/follow_line/web-template/launch/simple_line_follower_ros_headless.launch
This is in reference to issue #567
> Headless launch file for Follow Line Exercise

- exercises/follow_line/web-template/assets/gui.css
- exercises/follow_line/web-template/assets/ws_gui.js
- exercises/follow_line/web-template/gui.py
- exercises/follow_line/web-template/host.py
- exercises/follow_line/web-template/index.html
This is in reference to issue #574
> Update index and host of web template follow_line

- exercises/follow_line/web-template/assets/gui.css
- exercises/follow_line/web-template/assets/websocket_address.js
- exercises/follow_line/web-template/assets/ws_gui.js
- exercises/follow_line/web-template/gui.py
- exercises/follow_line/web-template/host.py
- exercises/follow_line/web-template/index.html
- exercises/follow_line/web-template/interfaces/pose3d.py
- exercises/follow_line/web-template/lap.py
This is in reference to issue #578 
The chronometer is now ready to be used!
> Chronometer in Follow Line Web Templates

- exercises/follow_line/web-template/launch/f1_circuit.world
- exercises/follow_line/web-template/launch/f1_circuit_headless.world
- exercises/obstacle_avoidance/web-template/launch/f1circuitobstacles.world
This is in reference to issue #594 
The world files are now updated!
> Update world files

- exercises/obstacle_avoidance/web-template/Parser.py
- exercises/obstacle_avoidance/web-template/assets/gui.css
- exercises/obstacle_avoidance/web-template/assets/map_view.js
- exercises/obstacle_avoidance/web-template/assets/ws_gui.js
- exercises/obstacle_avoidance/web-template/gui.py
- exercises/obstacle_avoidance/web-template/hal.py
- exercises/obstacle_avoidance/web-template/host.py
- exercises/obstacle_avoidance/web-template/index.html
- exercises/obstacle_avoidance/web-template/interfaces/laser.py
- exercises/obstacle_avoidance/web-template/lap.py
- exercises/obstacle_avoidance/web-template/launch/f1circuitobstacles.world
- exercises/obstacle_avoidance/web-template/map.py
- exercises/obstacle_avoidance/web-template/solution.txt
- exercises/obstacle_avoidance/web-template/targets_f1.json
This is in reference to issue #584 
The web-templates for obstacle avoidance are done, except a few small improvements and issues.
> Web Templates for Obstacle Avoidance

- exercises/obstacle_avoidance/web-template/README.md
- exercises/obstacle_avoidance/web-template/assets/websocket_address.js
This is in reference to issue #604
> [Web Template] Add documentation to Obstacle Avoidance exercise

- exercises/follow_line/web-template/README.md
> Follow line web-template README.md modified 

- exercises/obstacle_avoidance/web-template/assets/ws_gui.js
- exercises/obstacle_avoidance/web-template/map.py
This is in reference to issue #609
> [Web Templates] Fix lag in Laser Widget

- docs/_pages/exercises/IndustrialRobots/machine_vision.md
- docs/_pages/exercises/IndustrialRobots/mobile_manipulation.md
- docs/_pages/exercises/IndustrialRobots/pick_place.md
- exercises/machine_vision/MyAlgorithm.py
- exercises/mobile_manipulation/MyAlgorithm.py
> Change branch and remove extra arguments

- docs/_pages/exercises/AutonomousCars/web-templates/follow_line.md
This is in reference to issue #611 
Fix link to view the exercise web-page.
> [Web Templates] Add information to web-page

- docs/_pages/exercises/AutonomousCars/follow_line.md
- docs/_pages/exercises/AutonomousCars/obstacle_avoidance.md
This is in reference to issue #611 
Web Pages for both the Follow Line exercise and Obstacle Avoidance exercise are updated and ready to use.
> Instructions for Web Templates exercises

- exercises/follow_line/web-template/host.py
- exercises/obstacle_avoidance/web-template/assets/websocket_address.js
- exercises/obstacle_avoidance/web-template/host.py
This is in reference to issue #620 
The ping pong needed to be initialized before it can keep on going. This PR fixes that!
> [WebTemplates] Fix the connection closed issue

- docs/_pages/exercises/AutonomousCars/follow_line.md
- docs/_pages/exercises/AutonomousCars/obstacle_avoidance.md
- exercises/obstacle_avoidance/web-template/assets/websocket_address.js
This is in reference to issue #622
> [WebTemplates] Update instructions

- exercises/follow_line/web-template/assets/websocket_address.js
- exercises/follow_line/web-template/gui.py
- exercises/follow_line/web-template/hal.py
- exercises/follow_line/web-template/host.py
- exercises/follow_line/web-template/index.html
- exercises/obstacle_avoidance/web-template/host.py
- exercises/obstacle_avoidance/web-template/index.html
This is in reference to issue #624 
Solved by:
- Creating fake modules, using the library `imp`(dynamic module creation and update)
- Making fake modules available for the User
> [WebTemplates] Fix import issues

- exercises/follow_line/web-template/index.html
- exercises/obstacle_avoidance/web-template/assets/local_functions.js
- exercises/obstacle_avoidance/web-template/index.html
This is in reference to issue #627
> [WebTemplates] Add local load and save to Obstacle Avoidance

- docs/_pages/exercises/AutonomousCars/follow_line.md
- docs/_pages/exercises/AutonomousCars/obstacle_avoidance.md
- exercises/follow_line/web-template/assets/websocket_address.js
This is in reference to issue #638
> [WebTemplates] Update Documentation

- exercises/visual_lander/README.md
fixed some typo error in readme.md
> fixed some typo errors in visual_lander README.md

- docs/_pages/exercises/AutonomousCars/car-junction.md
- docs/_pages/exercises/AutonomousCars/follow_line.md
- docs/_pages/exercises/AutonomousCars/global_navigation.md
- docs/_pages/exercises/AutonomousCars/obstacle_avoidance.md
- docs/_pages/exercises/ComputerVision/3d_reconstruction.md
- docs/_pages/exercises/ComputerVision/color_filter.md
- docs/_pages/exercises/ComputerVision/visual_odometry.md
- docs/_pages/exercises/IndustrialRobots/machine_vision.md
- docs/_pages/exercises/IndustrialRobots/mobile_manipulation.md
- docs/_pages/exercises/IndustrialRobots/pick_place.md
- docs/_pages/exercises/MobileRobots/amazon_warehouse.md
- docs/_pages/exercises/MobileRobots/single_robot_amazon_warehouse.md
- docs/_pages/exercises/MobileRobots/vacuum_cleaner.md
- docs/_pages/exercises/MobileRobots/vacuum_cleaner_loc.md
I am starting out . So , I tried fixing some typos and spelling mistakes in the Exercise documentation.
> Fixed some Typos and Spelling mistakes in the Exercises docs.

- docs/_pages/exercises/MobileRobots/vacuum_cleaner.md
This is in reference to issue #661 
Update webpage of one exercise: Vacuum Cleaner without Localization
> [Documentation] Update Webpage Vacuum Cleaner without Localization

- exercises/drone_cat_mouse/my_solution.py
- exercises/drone_gymkhana/my_solution.py
- exercises/drone_hangar/my_solution.py
- exercises/follow_road/my_solution.py
- exercises/follow_turtlebot/my_solution.py
- exercises/labyrinth_escape/my_solution.py
- exercises/position_control/my_solution.py
- exercises/rescue_people/my_solution.py
- exercises/visual_lander/my_solution.py
> Added support to pose teleop in drone exercises

- exercises/follow_line/web-template/assets/websocket_address.js
- exercises/follow_line/web-template/assets/ws_gui.js
- exercises/follow_line/web-template/console.py
- exercises/follow_line/web-template/gui.py
- exercises/follow_line/web-template/hal.py
- exercises/follow_line/web-template/host.py
This is in reference to issue #653 
Integrating the changes in Follow Line exercise for Debugging.
> Refactor GUI WebSocket

- exercises/drone_cat_mouse/drone_cat_mouse.launch
- exercises/drone_cat_mouse/drone_cat_mouse.world
- exercises/drone_hangar/drone_hangar.launch
- exercises/drone_hangar/drone_hangar.world
- exercises/follow_road/follow_road.launch
- exercises/follow_road/follow_road.world
- exercises/follow_turtlebot/follow_turtlebot.launch
- exercises/follow_turtlebot/follow_turtlebot.world
- exercises/labyrinth_escape/labyrinth.world
- exercises/labyrinth_escape/labyrinth_escape.launch
- exercises/position_control/position_control.launch
- exercises/position_control/position_control.world
- exercises/rescue_people/rescue_people.launch
- exercises/rescue_people/rescue_people.world
- exercises/visual_lander/visual_lander.launch
- exercises/visual_lander/visual_lander.world
> Added world files to exercise folders

- exercises/drone_cat_mouse/drone_cat_mouse.launch
- exercises/drone_gymkhana/drone_gymkhana.launch
- exercises/drone_hangar/drone_hangar.launch
- exercises/follow_road/follow_road.launch
- exercises/follow_turtlebot/follow_turtlebot.launch
- exercises/labyrinth_escape/labyrinth_escape.launch
- exercises/position_control/position_control.launch
- exercises/rescue_people/rescue_people.launch
- exercises/visual_lander/visual_lander.launch
> Perspectives updated

- exercises/follow_line/web-template/assets/ws_gui.js
This is in reference to issue #653
> [Web-Template]Fix Canvas Image Error for Follow Line

- exercises/follow_line/web-template/assets/launcher.js
- exercises/follow_line/web-template/assets/ws_code.js
- exercises/follow_line/web-template/assets/ws_gui.js
- exercises/obstacle_avoidance/web-template/assets/launcher.js
- exercises/obstacle_avoidance/web-template/assets/ws_code.js
- exercises/obstacle_avoidance/web-template/assets/ws_gui.js
- exercises/vacuum_cleaner/web-template/assets/launcher.js
- exercises/vacuum_cleaner/web-template/assets/ws_code.js
- exercises/vacuum_cleaner/web-template/assets/ws_gui.js
- exercises/vacuum_cleaner_loc/web-template/assets/launcher.js
- exercises/vacuum_cleaner_loc/web-template/assets/ws_code.js
- exercises/vacuum_cleaner_loc/web-template/assets/ws_gui.js
This is in reference to issue #673 
`websocket_address` has been added as a function parameter to `declare_gui()` and `declare_code()` for the exercises: 
- Follow Line Exercise
- Obstacle Avoidance Exercise
- Vacuum Cleaner Exercise
- Vacuum Cleaner with Localization Exercise
> Add websocket_address as function parameter

- exercises/follow_road/follow_road.world
- exercises/follow_turtlebot/follow_turtlebot.launch
> Minor changes at follow_road and follow_turtlebot

- exercises/drone_cat_mouse/my_solution.py
- exercises/drone_gymkhana/my_solution.py
- exercises/drone_hangar/my_solution.py
- exercises/follow_road/my_solution.py
- exercises/follow_turtlebot/my_solution.py
- exercises/labyrinth_escape/my_solution.py
- exercises/position_control/my_solution.py
- exercises/rescue_people/my_solution.py
- exercises/visual_lander/my_solution.py
> Removed unused callbacks.

- docs/_pages/exercises.md
- docs/_pages/exercises/Drones/drone_cat_mouse.md
- docs/_pages/exercises/Drones/drones_section.md
- docs/_pages/installation.md
Drone cat-mouse exercise updated
> Drones installation updated to PX4 v1.11.3

- docs/_pages/exercises.md
- docs/_pages/exercises/Drones/drones_section.md
> All drone exercises updated to v2.1

- docs/_pages/installation.md
> Fixed bug on drone installation instructions

- exercises/visual_lander/visual_lander.world
> JdeRobot logo modified to avoid duplicity

- docs/_pages/installation.md
> Minor changes on drone installation instructions

- exercises/follow_line/web-template/assets/ws_code.js
- exercises/follow_line/web-template/assets/ws_gui.js
- exercises/follow_line/web-template/gui.py
- exercises/follow_line/web-template/host.py
- exercises/obstacle_avoidance/web-template/assets/ws_code.js
- exercises/obstacle_avoidance/web-template/assets/ws_gui.js
- exercises/obstacle_avoidance/web-template/gui.py
- exercises/obstacle_avoidance/web-template/host.py
- exercises/vacuum_cleaner/web-template/assets/ws_code.js
- exercises/vacuum_cleaner/web-template/assets/ws_gui.js
- exercises/vacuum_cleaner/web-template/gui.py
- exercises/vacuum_cleaner/web-template/host.py
- exercises/vacuum_cleaner_loc/web-template/assets/ws_code.js
- exercises/vacuum_cleaner_loc/web-template/assets/ws_gui.js
- exercises/vacuum_cleaner_loc/web-template/gui.py
- exercises/vacuum_cleaner_loc/web-template/host.py
Fixes #721 
The code websocket now communicates the brain and gui frequency. GUI websocket only handles the GUI portion of the software.
> Refactor websocket communication

- exercises/follow_line/web-template/gui.py
> Updating RADI for unibotics follow line to get v and w

- exercises/follow_line/web-template/README.md
- exercises/obstacle_avoidance/web-template/README.md
- exercises/vacuum_cleaner/web-template/README.md
- exercises/vacuum_cleaner_loc/web-template/README.md
- scripts/README.md
> Split Documentation for Users and Developers

- exercises/follow_line/web-template/console.py
- exercises/follow_line/web-template/host.py
- exercises/obstacle_avoidance/web-template/console.py
- exercises/obstacle_avoidance/web-template/host.py
- exercises/vacuum_cleaner/web-template/console.py
- exercises/vacuum_cleaner/web-template/host.py
- exercises/vacuum_cleaner_loc/web-template/console.py
- exercises/vacuum_cleaner_loc/web-template/host.py
- scripts/README.md
This is in reference to issue #741 
- Type convert messages to be print by `console.py`
- Avoid timeout by `ws_code` websocket, the connection automatically closes after some inactivity. Fixed by adding exchange of frequency messages.
> Fix bugs with pseudo console and timeout 

- docs/_pages/installation.md
> Drones installation instruction updated

- scripts/Dockerfile
Added temporary installation: drone_wrapper from source until new ROS pkg is released
> New temporary dockerfile

- exercises/follow_line/web-template/assets/gui.css
- exercises/follow_line/web-template/assets/ws_gui.js
- exercises/follow_line/web-template/exercise.html
In reference to issue #737 
This update optimizes the Browser part of the Web Templates. The browser now takes lesser CPU power, allowing RADI to utilize more power.
Changes in this update: Replace the `<canvas>` tag with `<image>` tag
> [Web Templates] Optimization in Browser side

- docs/_pages/exercises/AutonomousCars/follow_line.md
On line 113 of follow_line.md, index.html is changed to exercise.html
> Correction in documentation of follow line exercise

- exercises/drone_cat_mouse/web-template/assets/main.css
- exercises/drone_cat_mouse/web-template/assets/ws_gui.js
- exercises/drone_cat_mouse/web-template/exercise.html
- exercises/drone_cat_mouse/web-template/exercise.py
- exercises/drone_cat_mouse/web-template/gui.py
- exercises/drone_cat_mouse/web-template/hal.py
- exercises/drone_cat_mouse/web-template/mouse.py
First version, drones seems to be unstable. More test are required.
Closes #671
> Releasing drone-cat-mouse exercise on web templates

- scripts/Dockerfile
> Removing temporary drone dependencies from dockerfile

- exercises/obstacle_avoidance/web-template/assets/gui.css
- exercises/obstacle_avoidance/web-template/assets/ws_gui.js
- exercises/obstacle_avoidance/web-template/exercise.html
- exercises/vacuum_cleaner/web-template/assets/ws_gui.js
- exercises/vacuum_cleaner_loc/web-template/assets/ws_gui.js
In reference to issue #737 
The other exercise that can benefit from the Browser side optimization (`<canvas>` to `<img>` tag) is the Obstacle Avoidance exercise, which has been updated, in this PR.
> Browser side optimization of Obstacle Avoidance

- docs/_pages/exercises/Drones/drone_cat_mouse.md
- exercises/drone_cat_mouse/my_solution.py
- exercises/drone_cat_mouse/web-template/exercise.py
- exercises/drone_cat_mouse/web-template/hal.py
Currently, the only differences are on showing images in the web or rqt tool.
| ROSNode | Web |
| - | - |
| set_image_filtered(cv2_img) | showImage(cv2_img) |
| set_image_threshed(cv2_img) | showLeftImage(cv2_img) |
> Minimizing API differences between rosnode and web templates

- exercises/drone_cat_mouse/drone_cat_mouse.world
- exercises/drone_cat_mouse/web-template/drone_cat_mouse.world
- scripts/Dockerfile
> Visual updates to drone_cat_mouse exercise

- docs/_pages/installation.md
Fixed Minor Typo errors for RoboticsAcademy 2.1 and 2.0 release
> Update installation.md :  Fix minor typo errors

- exercises/drone_cat_mouse/web-template/assets/main.css
- exercises/drone_cat_mouse/web-template/assets/ws_gui.js
- exercises/drone_cat_mouse/web-template/exercise.html
- exercises/drone_cat_mouse/web-template/gui.py
- exercises/drone_cat_mouse/web-template/interfaces/threadStoppable.py
- exercises/drone_cat_mouse/web-template/mouse.py
> New buttons: play, pause and reset mouse

- docs/_pages/exercises/IndustrialRobots/pick_place.md
Update IndustrialRobots Repo link to `https://github.com/JdeRobot/IndustrialRobots.git`
Resolves : #802
> [IndustrialRobots] Update Pick Place Docs

- exercises/follow_line/web-template/launch/f1_circuit.world
- exercises/follow_line/web-template/launch/f1_circuit_headless.world
This commit makes modifications only in the web-template files of the FollowLine exercise. I have tested it by manually mounting the launch directory to Docker from my local system.
> Added sky and clouds in FollowLine exercise. Solves issue #783

- docs/_pages/exercises/AutonomousCars/obstacle_avoidance.md
- docs/_pages/exercises/Drones/drone_cat_mouse.md
- docs/_pages/exercises/MobileRobots/vacuum_cleaner.md
- docs/_pages/exercises/MobileRobots/vacuum_cleaner_loc.md
- exercises/assets/js/utils.js
- exercises/drone_cat_mouse/web-template/assets/launcher.js
- exercises/drone_cat_mouse/web-template/drone_cat_mouse.world
- exercises/drone_cat_mouse/web-template/exercise.html
- exercises/follow_line/web-template/assets/launcher.js
- exercises/follow_line/web-template/exercise.html
- exercises/obstacle_avoidance/web-template/assets/launcher.js
- exercises/obstacle_avoidance/web-template/exercise.html
- exercises/obstacle_avoidance/web-template/launch/f1circuitobstacles.world
- exercises/vacuum_cleaner/web-template/assets/launcher.js
- exercises/vacuum_cleaner/web-template/exercise.html
- exercises/vacuum_cleaner/web-template/launch/roomba_1_house.world
- exercises/vacuum_cleaner_loc/web-template/assets/launcher.js
- exercises/vacuum_cleaner_loc/web-template/exercise.html
- exercises/vacuum_cleaner_loc/web-template/launch/roomba_1_house.world
- scripts/manager.py
This PR fixes #790 
A few things to note, which I want to be reviewed specifically:
1) I have created a new JS file utils.js since functionality is common for all exercises. But the downside to this would be the relative path used in script tag. 
2) Instead of completely removing gzweb I have just added more exercises to the earlier list of gzclient exercises in `manager.py`.
> novnc for other exercises (fixes #790)

- scripts/Dockerfile
In reference to issue #800 
Fix some small errors with Dockerfile
> Fix errors with Dockerfile

- exercises/drone_cat_mouse/web-template/assets/ws_gui.js
> added variable to lock function

- exercises/follow_line/web-template/console.py
- exercises/follow_line/web-template/exercise.py
This is in reference to issue #800 
This fixes a bug with ConsoleVNC. The console will now still work for arbitrary number of refreshes.
This change is only related to the Follow Line exercise
> [ConsoleVNC] Fix bugs with console

- exercises/drone_cat_mouse/web-template/RADI-launch
> Added vnc port

- docs/_pages/exercises.md
- docs/_pages/exercises/Drones/drone_cat_mouse.md
- docs/_pages/exercises/Drones/drones_section.md
- docs/_pages/exercises/Drones/follow_turtlebot.md
- exercises/follow_turtlebot/follow_turtlebot.world
- exercises/follow_turtlebot/web-template/README.md
- exercises/follow_turtlebot/web-template/follow_turtlebot.world
> [follow turtlebot] Update readme, webpage and add clouds

- exercises/follow_turtlebot/follow_turtlebot.world
- exercises/follow_turtlebot/my_solution.py
- exercises/follow_turtlebot/web-template/follow_turtlebot.world
Added jderobot logo
ROS node template updated to match API instructions: drone --> HAL
#806
> [follow turtlebot] Minor improvements

- scripts/README.md
Update port mapping in the Installation Instructions
> [RADI] Update README

- exercises/3d_reconstruction/web-template/launch/kobuki_1_reconstruccion3d.world
> Improve lights exercise 3D-Reconstruction

- docs/_pages/exercises/ComputerVision/color_filter.md
> updating color_filter.md

- docs/_pages/exercises/Drones/drone_hangar.md
- docs/_pages/exercises/Drones/follow_road.md
- exercises/drone_hangar/colorTuner.conf
- exercises/follow_road/colorTuner.conf
- exercises/follow_turtlebot/README.md
- exercises/follow_turtlebot/colorTuner.conf
> clean ColorTuner from drone exercises

- exercises/follow_turtlebot/web-template/assets/main.css
- exercises/follow_turtlebot/web-template/assets/ws_gui.js
- exercises/follow_turtlebot/web-template/exercise.html
- exercises/follow_turtlebot/web-template/exercise.py
- exercises/follow_turtlebot/web-template/gui.py
- exercises/follow_turtlebot/web-template/launch/follow_turtlebot.launch
- exercises/follow_turtlebot/web-template/turtlebot.py
> add play,pause and reset buttons to control ground turtlebot

- exercises/follow_line/web-template/assets/ws_code.js
- exercises/follow_line/web-template/exercise.html
- exercises/follow_line/web-template/exercise.py
Solves Issue #843 
This is how the final render looks(compare RTF in the table and in Gazebo VNC). I have described my changes via verbose commit messages.
> Display Real time factor in the follow_line's exercise webpage

- exercises/static/exercises/obstacle_avoidance/web-template/assets/map_view.js
> Change in the coordinate axes for visualization

- docs/_pages/exercises/Drones/follow_road.md
- docs/_pages/exercises/Drones/follow_turtlebot.md
Sorry for the misunderstanding
> Added new maintainers to drone exercises

- exercises/templates/exercises/color_filter/exercise.html
- exercises/templates/exercises/drone_cat_mouse/exercise.html
- exercises/templates/exercises/follow_turtlebot/exercise.html
- exercises/templates/exercises/obstacle_avoidance/exercise.html
- exercises/templates/exercises/vacuum_cleaner/exercise.html
- exercises/templates/exercises/vacuum_cleaner_loc/exercise.html
> VNC Based Console for Issue 913

- docs/_pages/exercises/AutonomousCars/follow_line.md
- docs/_pages/exercises/AutonomousCars/obstacle_avoidance.md
- docs/_pages/exercises/ComputerVision/3d_reconstruction.md
- docs/_pages/exercises/ComputerVision/color_filter.md
- docs/_pages/exercises/Drones/drone_cat_mouse.md
- docs/_pages/exercises/Drones/follow_road.md
- docs/_pages/exercises/Drones/follow_turtlebot.md
- docs/_pages/exercises/MobileRobots/vacuum_cleaner.md
- docs/_pages/exercises/MobileRobots/vacuum_cleaner_loc.md
- exercises/static/exercises/drone_cat_mouse/web-template/RADI-launch
- exercises/static/exercises/drone_cat_mouse/web-template/README.md
- exercises/static/exercises/follow_road/web-template/RADI-launch
- exercises/static/exercises/follow_road/web-template/README.md
- exercises/static/exercises/follow_turtlebot/web-template/RADI-launch
- exercises/static/exercises/follow_turtlebot/web-template/README.md
- scripts/README.md
Now the instructions use the unified RADI launch and the Django webserver to open the exercise pages.
> Updated RADI launch instructions

- exercises/static/exercises/3d_reconstruction/web-template/assets/ws_code.js
- exercises/static/exercises/color_filter/web-template/assets/ws_code.js
- exercises/static/exercises/drone_cat_mouse/web-template/assets/ws_code.js
- exercises/static/exercises/follow_line/web-template/assets/ws_code.js
- exercises/static/exercises/follow_turtlebot/web-template/assets/ws_code.js
- exercises/static/exercises/obstacle_avoidance/web-template/assets/ws_code.js
- exercises/static/exercises/vacuum_cleaner/web-template/assets/ws_code.js
- exercises/static/exercises/vacuum_cleaner_loc/web-template/assets/ws_code.js
- Handles error when sending code before connecting to backend and alerts the user.
- "Code sent" message is now only written when the code truly is sent.
> submitCode function error handling

- exercises/static/exercises/3d_reconstruction/web-template/assets/ws_code.js
- exercises/static/exercises/3d_reconstruction/web-template/assets/ws_gui.js
- exercises/static/exercises/color_filter/web-template/assets/ws_code.js
- exercises/static/exercises/color_filter/web-template/assets/ws_gui.js
- exercises/static/exercises/drone_cat_mouse/web-template/assets/ws_code.js
- exercises/static/exercises/drone_cat_mouse/web-template/assets/ws_gui.js
- exercises/static/exercises/follow_line/web-template/assets/ws_code.js
- exercises/static/exercises/follow_line/web-template/assets/ws_gui.js
- exercises/static/exercises/follow_turtlebot/web-template/assets/ws_code.js
- exercises/static/exercises/follow_turtlebot/web-template/assets/ws_gui.js
- exercises/static/exercises/obstacle_avoidance/web-template/assets/ws_code.js
- exercises/static/exercises/obstacle_avoidance/web-template/assets/ws_gui.js
- exercises/static/exercises/vacuum_cleaner/web-template/assets/ws_code.js
- exercises/static/exercises/vacuum_cleaner/web-template/assets/ws_gui.js
- exercises/static/exercises/vacuum_cleaner_loc/web-template/assets/ws_code.js
- exercises/static/exercises/vacuum_cleaner_loc/web-template/assets/ws_gui.js
Each websocket checks the readyState of the other and only the second one connecting displays the message.
> Connection established popup displays once

- exercises/static/exercises/follow_road/follow_road.launch
- exercises/static/exercises/follow_road/follow_road.world
Added the world file of Web Templates to ROS Node Templates as well (issue #935 )
> Fix issue-935

- exercises/static/exercises/vacuum_cleaner/web-template/exercise.py
- exercises/static/exercises/vacuum_cleaner_loc/web-template/exercise.py
Adds .getLaserData() and .getPose3d() in Vacuum Cleaner and .getLaserData() in Vacuum Cleaner Loc.
> Added functions to Vacuum Cleaner exercises

- docs/_pages/exercises/MobileRobots/vacuum_cleaner.md
- docs/_pages/exercises/MobileRobots/vacuum_cleaner_loc.md
Replaced the use of self. for HAL.
> Updated Vacuum exercises documentation

- docs/_pages/exercises/ComputerVision/color_filter.md
> Updated Color Filter launch instructions

- exercises/static/exercises/drone_cat_mouse/web-template/exercise.py
> Minor fixes

- scripts/Dockerfile-noetic
> Changed the tag of PX4 and updated gazebo model path

- exercises/static/exercises/dl_digit_classifier/web-template/exercise.py
- Now the number of consecutive frames with the same output needed for prediction will not be constant, but will rather depend on the instantaneous frame rate of the host hardware( n_consecutive_frames = fps/2).
- Added FPS counter.
> Made consistent frame rate policy and added FPS counter

- exercises/static/exercises/3d_reconstruction/web-template/assets/main.css
- exercises/static/exercises/3d_reconstruction/web-template/assets/ws_code.js
- exercises/static/exercises/color_filter/web-template/assets/main.css
- exercises/static/exercises/color_filter/web-template/assets/ws_code.js
- exercises/static/exercises/drone_cat_mouse/web-template/assets/main.css
- exercises/static/exercises/drone_cat_mouse/web-template/assets/ws_code.js
- exercises/static/exercises/follow_line/web-template/assets/main.css
- exercises/static/exercises/follow_line/web-template/assets/ws_code.js
- exercises/static/exercises/follow_road/web-template/assets/main.css
- exercises/static/exercises/follow_road/web-template/assets/ws_code.js
- exercises/static/exercises/follow_turtlebot/web-template/assets/main.css
- exercises/static/exercises/follow_turtlebot/web-template/assets/ws_code.js
- exercises/static/exercises/obstacle_avoidance/web-template/assets/main.css
- exercises/static/exercises/obstacle_avoidance/web-template/assets/ws_code.js
- exercises/static/exercises/vacuum_cleaner/web-template/assets/main.css
- exercises/static/exercises/vacuum_cleaner/web-template/assets/ws_code.js
- exercises/static/exercises/vacuum_cleaner_loc/web-template/assets/main.css
- exercises/static/exercises/vacuum_cleaner_loc/web-template/assets/ws_code.js
- exercises/templates/base.html
- exercises/templates/base_ng.html
- exercises/templates/base_no_RTF.html
- exercises/templates/exercises/follow_road/exercise.html
Now the denominator can be modified to the desired frequency
> Improvement to Frontend

- docs/_pages/exercises.md
- docs/_pages/exercises/Drones/drone_cat_mouse.md
- docs/_pages/exercises/Drones/drones_section.md
> Updated webpage of drone-cat-mouse exercise

- scripts/Dockerfile-2.4
- scripts/start.sh
> Source installation of jderobot drones inside RADI

- _pages/exercises/ComputerVision/dl_digit_classifier.md
> Fix video id

- academy/settings.py
- exercises/static/exercises/follow_line/web-template/assets/launcher.js
- exercises/templates/exercises/follow_line/exercise.html
- scripts/manager.py
In reference to issue #903 
Only for Follow Line exercise
> On Demand Gzclient

- _pages/exercises.md
- _pages/exercises/Drones/drones_section.md
> Fixes wrong path in rescue people

- _pages/exercises.md
- _pages/exercises/Drones/drone_gymkhana.md
- _pages/exercises/Drones/drone_hangar.md
- _pages/exercises/Drones/drones_section.md
- _pages/exercises/Drones/rescue_people.md
- _pages/exercises/Drones/visual_lander.md
> Update webpages of 4 drones exercise, drones section and main exercise page

- _pages/exercises/Drones/drone_gymkhana.md
> Fixed typo in drone gymkhana

- _pages/exercises/Drones/labyrinth_escape.md
- _pages/exercises/Drones/position_control.md
- _pages/exercises/Drones/rescue_people.md
> Added youtube links to the web template teaser videos of 3 drone exercises

- exercises/static/exercises/follow_line/web-template/assets/launcher.js
- exercises/static/exercises/follow_line/web-template/assets/ws_code.js
- exercises/static/exercises/follow_line/web-template/exercise.py
- scripts/manager.py
In reference to issue #1089. Step 1 of the process.
The simulation control (currently only reset functionality) has been added to Follow Line exercise.
> [Follow Line] Add simulation control to manager 

- academy/settings.py
- exercises/static/exercises/drone_cat_mouse/web-template/assets/ws_code.js
- exercises/static/exercises/drone_cat_mouse/web-template/exercise.py
- exercises/static/exercises/drone_gymkhana/web-template/exercise.py
- exercises/static/exercises/drone_hangar/web-template/exercise.py
- exercises/static/exercises/follow_road/web-template/exercise.py
- exercises/static/exercises/follow_turtlebot/web-template/exercise.py
- exercises/static/exercises/labyrinth_escape/web-template/exercise.py
- exercises/static/exercises/position_control/web-template/exercise.py
- exercises/static/exercises/rescue_people/web-template/exercise.py
- exercises/static/exercises/visual_lander/web-template/exercise.py
> [noetic] Fixes connection timeout

- _pages/exercises/Drones/drone_gymkhana.md
- _pages/exercises/Drones/follow_road.md
- _pages/exercises/Drones/visual_lander.md
Closes issue #1145 and changed the cube positions mentioned in Drone Gymkhana exercise webpage
> Added youtube links to teaser videos of Follow Road, Drone Gymkhana and Visual Lander

- _pages/exercises/Drones/drone_cat_mouse.md
- _pages/exercises/Drones/follow_turtlebot.md
> Added youtube links to teaser videos of Drone cat mouse and Follow turtlebot

- scripts/build.sh
> Updated build.sh

- academy/settings.py
- exercises/static/exercises/human_detection/web-template/assets/launcher.js
- exercises/static/exercises/human_detection/web-template/assets/ws_code.js
- exercises/static/exercises/human_detection/web-template/assets/ws_gui.js
- exercises/templates/base_DL.html
- exercises/templates/exercises/human_detection/exercise.html
> One RADI launch per session for human detection exercise

- exercises/static/exercises/follow_line/web-template/brain_guest.py
- exercises/static/exercises/follow_line/web-template/exercise_guest.py
- exercises/static/exercises/follow_line/web-template/gui_guest.py
- exercises/static/exercises/follow_line/web-template/hal_guest.py
- exercises/static/exercises/follow_line/web-template/user_functions_guest.py
Added exercise_guest.py, brain_guest.py, hal_guest.py and gui_guest.py used for the exercises where two cars are involved.
> Issue 1189

- exercises/static/exercises/follow_line/web-template/brain_guest.py
- scripts/manager.py
follow_line_game is now part of the circuit exercises.
before checking code, now its checked if the exercise is part of the follow_line challenge.
> Fix GUI and HAL modules generation

- exercises/static/exercises/human_detection/web-template/assets/main.css
- exercises/static/exercises/human_detection/web-template/assets/ws_code.js
- exercises/static/exercises/human_detection/web-template/exercise.py
- exercises/templates/base_DL.html
- exercises/templates/exercises/human_detection/exercise.html
Code clean up for the human detection exercise
> code clean-up

- _pages/exercises/Drones/drone_cat_mouse.md
- _pages/exercises/Drones/drone_gymkhana.md
- _pages/exercises/Drones/drone_hangar.md
- _pages/exercises/Drones/follow_road.md
- _pages/exercises/Drones/follow_turtlebot.md
- _pages/exercises/Drones/labyrinth_escape.md
- _pages/exercises/Drones/position_control.md
- _pages/exercises/Drones/rescue_people.md
- _pages/exercises/Drones/visual_lander.md
> Added instructions on how to save terminal output

- _pages/exercises.md
- _pages/exercises/AutonomousCars/autonomous_cars_section.md
- _pages/exercises/AutonomousCars/global_navigation.md
> Update global navigation documentation

- exercises/templates/exercises/global_navigation/exercise.html
> Update function for Global Navigation

- _pages/exercises/Drones/drone_cat_mouse.md
- _pages/exercises/Drones/drone_gymkhana.md
- _pages/exercises/Drones/drone_hangar.md
- _pages/exercises/Drones/follow_road.md
- _pages/exercises/Drones/follow_turtlebot.md
- _pages/exercises/Drones/labyrinth_escape.md
- _pages/exercises/Drones/position_control.md
- _pages/exercises/Drones/rescue_people.md
- _pages/exercises/Drones/visual_lander.md
> [gh-pages] Updated log instructions for all drone exercises

- exercises/static/exercises/rescue_people/web-template/launch/px4.launch
- exercises/static/exercises/rescue_people/web-template/rescue_people.world
> Redesigned Rescue People

- _pages/exercises/AutonomousCars/car-junction.md
- _pages/exercises/AutonomousCars/follow_line.md
- _pages/exercises/AutonomousCars/global_navigation.md
- _pages/exercises/AutonomousCars/obstacle_avoidance.md
- _pages/exercises/ComputerVision/3d_reconstruction.md
- _pages/exercises/ComputerVision/color_filter.md
- _pages/exercises/ComputerVision/dl_digit_classifier.md
- _pages/exercises/ComputerVision/human_detection.md
- _pages/exercises/ComputerVision/montecarlo_visual_loc.md
- _pages/exercises/ComputerVision/opticalflow_teleop.md
- _pages/exercises/ComputerVision/visual_odometry.md
- _pages/exercises/Drones/drone_cat_mouse.md
- _pages/exercises/Drones/drone_gymkhana.md
- _pages/exercises/Drones/drone_hangar.md
- _pages/exercises/Drones/follow_road.md
- _pages/exercises/Drones/follow_turtlebot.md
- _pages/exercises/Drones/labyrinth_escape.md
- _pages/exercises/Drones/position_control.md
- _pages/exercises/Drones/rescue_people.md
- _pages/exercises/Drones/visual_lander.md
- _pages/exercises/IndustrialRobots/machine_vision.md
- _pages/exercises/IndustrialRobots/mobile_manipulation.md
- _pages/exercises/IndustrialRobots/pick_place.md
- _pages/exercises/MobileRobots/amazon_warehouse.md
- _pages/exercises/MobileRobots/laser_mapping.md
- _pages/exercises/MobileRobots/vacuum_cleaner.md
- _pages/exercises/MobileRobots/vacuum_cleaner_loc.md
Update Videos and Instructions titles.
> Documentation titles update

- _pages/exercises/Drones/rescue_people.md
> Updated video with new reference solution

- _pages/exercises/AutonomousCars/obstacle_avoidance.md
Reverts JdeRobot/RoboticsAcademy#1421 until the new RADI is released
> Revert "Issue 1420"

- exercises/static/exercises/rescue_people/rescue_people.launch
- exercises/static/exercises/rescue_people/rescue_people.world
Though the version will eventually be remove in the future but I just pushed the changes for the reference
> Matched the world of rescue_people exercise in v2.1 to v2.3

- exercises/static/exercises/global_navigation/web-template/assets/birds_eye.js
- exercises/static/exercises/global_navigation/web-template/assets/generatepath.js
- exercises/static/exercises/global_navigation/web-template/assets/ws_gui.js
- exercises/static/exercises/global_navigation/web-template/exercise.html
- exercises/templates/exercises/global_navigation/exercise.html
-Pointer display fix when you click in canvas.
-Add a Jquery library to be able to use '$' in generatepath.js file.
-Visual interface equal to Unibotics Exercises
> Fixes global navigation GUI

- scripts/Dockerfile.base
> Fixed broken link in dockerfile

- README.md
In this update i added:
1. Links to the branches.
2. Information about the manager websocket
3. Information about the 'issues' branches, it's the same info we have in other repositories such as unibotics-exercises.
> Improve documentation for developers

- _pages/exercises.md
- _pages/exercises/AutonomousCars/autonomous_cars_section.md
- _pages/exercises/ComputerVision/computer_vision_section.md
- _pages/exercises/Drones/drones_section.md
- _pages/exercises/MobileRobots/mobile_robots_section.md
> Updated tag with radi version

- README.md
Made introduction more descriptive
> chore: Updated introduction

- exercises/templates/exercises/human_detection/exercise.html
- static/exercises/human_detection/js/ws_code.js
- static/exercises/human_detection/js/ws_gui.js
> Resolved human_detection launch issue

- scripts/README.md
> Update scripts README.md

- exercises/templates/exercises/power_tower_inspection/exercise.html
> Issue 1595

- _pages/exercises.md
- _pages/exercises/Drones/drones_section.md
- _pages/exercises/Drones/package_delivery.md
> Add package delivery youtube video

- scripts/Dockerfile.base
- scripts/README.md
> Dockerfile documentation

- exercises/static/exercises/drone_cat_mouse/web-template/launch/launch.py
- exercises/static/exercises/drone_gymkhana/web-template/launch/launch.py
- exercises/static/exercises/drone_hangar/web-template/launch/launch.py
- exercises/static/exercises/follow_road/web-template/launch/launch.py
- exercises/static/exercises/follow_turtlebot/web-template/launch/launch.py
- exercises/static/exercises/labyrinth_escape/web-template/launch/launch.py
- exercises/static/exercises/package_delivery/web-template/launch/launch.py
- exercises/static/exercises/position_control/web-template/launch/launch.py
- exercises/static/exercises/power_tower_inspection/web-template/launch/launch.py
- exercises/static/exercises/rescue_people/web-template/launch/launch.py
- exercises/static/exercises/visual_lander/web-template/launch/launch.py
> New launch files for multiple drones check upd code

- .gitignore
- CONTRIBUTING.md
> Adding contributing guide lines

- scripts/Dockerfile-foxy.base
> Updated TurboVNC and VirtualGL download in Dockerfile-foxy.base

- LICENSE
GNU GPLv3 license file added
Fix #1784
> New: add license file

- exercises/static/exercises/drone_cat_mouse/web-template/launch/drone_cat_mouse.launch
- exercises/static/exercises/follow_turtlebot/web-template/launch/follow_turtlebot.launch
minor bug solve in rotors integration
Closes #1797
> [drones] solved param tag issue 

- docs/InstructionsForDevelopers.md
Contributes towards #1794
- Added Documentation to edit code on RADI on the GO.
> Update Docker Development Instructions

- README.md
- docs/InstructionsForDevelopers.md
- - Added developer instructions to mount local code repository to RADI
> Update Developer Documentation

- scripts/Dockerfile
- scripts/manager.py
catkin ignore crazsyS and mav_comm while we look for a better solution (#1840)
> [drones] Restoring PX4 to fly again in RA

- exercises/static/exercises/follow_line/web-template/launch/prototype_f1_circuit_headless_default.world
- exercises/static/exercises/follow_line/web-template/launch/prototype_f1_circuit_headless_montmelo.world
- exercises/static/exercises/follow_line/web-template/launch/prototype_f1_circuit_headless_montreal.world
- exercises/static/exercises/follow_line/web-template/launch/prototype_f1_circuit_headless_nbg.world
I have updated the models in the world file with f1_renault.
> solved Issue #1910 [follow_line] Model visual details not displaying well

- src/manager/manager.py
This pull request solves issue #1960
> Using signal handler to close RAM

- react_frontend/src/components/buttons/ConsoleButton.js
- react_frontend/src/components/buttons/GazeboButton.js
- react_frontend/src/components/buttons/RAM/RAMExerciseConfiguration.js
- react_frontend/src/components/buttons/RAM/RAMPlayPause.js
- react_frontend/src/components/buttons/RAM/RAMStop.js
- react_frontend/src/components/buttons/RAMVisualizatorButton.js
- react_frontend/src/components/common/MainAppBar.js
- react_frontend/src/components/common/RAM/RAMExerciseControl.js
- react_frontend/src/components/exercises/GazeboViewer.js
- react_frontend/src/components/templates/FollowLineReactRAM.js
- react_frontend/src/components/views/RAM/RAMFollowLineExerciseView.js
- react_frontend/src/components/views/RAM/RAMVacuumCleanerExerciseView.js
- react_frontend/src/components/views/Visualization.js
- react_frontend/src/components/visualizers/RAM/RAMFrequency.js
- react_frontend/src/contexts/NewManagerExerciseContext.js
This pull request solves issue #1964
> Minor frontend refinements

- exercises/static/exercises/visual_lander/web-template/visual_lander.world
> Visual Lander front-end

- exercises/static/exercises/power_tower_inspection/web-template/power_tower_inspection.world
From Prakarsh gsoc (#1795)
Rust defects are flying, it doesn't happen in master. Won't merge?
> Frontend Power Tower update

- _pages/exercises/AutonomousCars/autoparking.md
- _pages/exercises/AutonomousCars/car-junction.md
- _pages/exercises/AutonomousCars/follow_line.md
- _pages/exercises/AutonomousCars/global_navigation.md
- _pages/exercises/AutonomousCars/obstacle_avoidance.md
- _pages/exercises/ComputerVision/3d_reconstruction.md
- _pages/exercises/ComputerVision/montecarlo_visual_loc.md
- _pages/exercises/Drones/drone_cat_mouse.md
- _pages/exercises/Drones/drone_gymkhana.md
- _pages/exercises/Drones/drone_hangar.md
- _pages/exercises/Drones/follow_road.md
- _pages/exercises/Drones/follow_turtlebot.md
- _pages/exercises/Drones/labyrinth_escape.md
- _pages/exercises/Drones/package_delivery.md
- _pages/exercises/Drones/position_control.md
- _pages/exercises/Drones/power_tower_inspection.md
- _pages/exercises/Drones/rescue_people.md
- _pages/exercises/Drones/visual_lander.md
- _pages/exercises/MobileRobots/laser_mapping.md
- _pages/exercises/MobileRobots/vacuum_cleaner.md
- _pages/exercises/MobileRobots/vacuum_cleaner_loc.md
- _pages/gpu_acceleration.md
- _pages/installation.md
> Added RAM port

- exercises/static/exercises/autoparking/web-template/launch/autoparking.launch
- exercises/static/exercises/autoparking_react/web-template/launch/autoparking.launch
Fixes #1980 
@jmplaza @pariaspe
> corrected path for autoparking

- _pages/exercises/AutonomousCars/car-junction.md
- _pages/exercises/AutonomousCars/follow_line.md
- _pages/exercises/AutonomousCars/global_navigation.md
- _pages/exercises/AutonomousCars/obstacle_avoidance.md
- _pages/exercises/ComputerVision/3d_reconstruction.md
- _pages/exercises/ComputerVision/montecarlo_visual_loc.md
- _pages/exercises/Drones/drone_cat_mouse.md
- _pages/exercises/Drones/drone_gymkhana.md
- _pages/exercises/Drones/drone_hangar.md
- _pages/exercises/Drones/follow_road.md
- _pages/exercises/Drones/follow_turtlebot.md
- _pages/exercises/Drones/labyrinth_escape.md
- _pages/exercises/Drones/package_delivery.md
- _pages/exercises/Drones/position_control.md
- _pages/exercises/Drones/power_tower_inspection.md
- _pages/exercises/Drones/rescue_people.md
- _pages/exercises/Drones/visual_lander.md
- _pages/exercises/MobileRobots/laser_mapping.md
- _pages/exercises/MobileRobots/vacuum_cleaner.md
- _pages/exercises/MobileRobots/vacuum_cleaner_loc.md
#1986 
@jmplaza Updated the rest of the Exercises. Can close the issue.
> updated exercises with new link for gpu_acceleration

- exercises/templates/exercise_base.html
> Added hyperlink to home

- src/libs/applications/compatibility/robotics_application_wrapper.py
- src/manager/launcher/launcher_robot_display_view.py
Includes a new VNC launch script and a new IRoboticsApplication implementation
> Added RAM PythonWebIDE compatibility

- react_frontend/src/components/common/MainAppBar.js
> Retry connection and Launch on RR exercises

- exercises/static/exercises/human_detection/exercise.py
Fixes #2007 by starting the console at a more appropriate place
> moved start_console to a later stage

- react_frontend/src/components/DrawerAppBar.js
This should fix other issues as mentioned in continued #2027 now.
**Changes Made**
**Log** when command `./build.sh -f test` is run in the terminal looks like-
```bash
sudo ./build.sh -f test                       
BUILDING Jderobot BASE IMAGE =====================
[+] Building 1.7s (34/34) FINISHED                                                            
=> [internal] load build definition from Dockerfile.base                                0.0s
=> => transferring dockerfile: 10.61kB                                                  0.0s
=> [internal] load .dockerignore                                                        0.0s
=> => transferring context: 2B                                                          0.0s
=> [internal] load metadata for …
```
> Forum hyperlink

- scripts/mini_RADI/.env
- scripts/mini_RADI/Dockerfile.humble-base
- scripts/mini_RADI/Dockerfile.mini_humble
- scripts/mini_RADI/build.sh
Solves #2091 
[Work in progress]
> [Draft] Simplified Mini RADI Dockerfile to fasten build times

- scripts/mini_RADI/Dockerfile.mini_humble
https://github.com/JdeRobot/RoboticsInfrastructure/pull/290
https://github.com/JdeRobot/RoboticsInfrastructure/issues/280
> moved gazebo models path to .env in RoboticsInfrastructure

- README.md
- scripts/mini_RADI/README.md
https://github.com/JdeRobot/RoboticsInfrastructure/issues/277
> mini RADI structure readme added

- scripts/mini_RADI/Dockerfile.dependencies_humble
added lxde-common package to fix GPU acceleration un mini-RADI humble
> issue-2132: GPU acceleration

- scripts/mini_RADI/Dockerfile.dependencies_humble
- scripts/mini_RADI/Dockerfile.mini_humble
[#278](https://github.com/JdeRobot/RoboticsInfrastructure/issues/278)
> ROS2 PX4 addition

- scripts/mini_RADI/Dockerfile.dependencies_humble
- scripts/mini_RADI/Dockerfile.dependencies_noetic
> Fix for node installation

- scripts/mini_RADI/Dockerfile.dependencies_humble
- scripts/mini_RADI/Dockerfile.mini_humble
Added Aerostack2 build to RADI
Made a workspace solely for drone packages:
-  aerostack2
- px4_msgs
- px4_ros_com
Fixes #2154
> Aerostack2 and workspace for drones added

- scripts/mini_RADI/Dockerfile.dependencies_humble
Fixes https://github.com/JdeRobot/RoboticsApplicationManager/issues/45
> Pydantic quick fix

- docs/InstructionsForDevelopers.md
Fixes Missing dependecies 
Fix to #2167
> Fixed Missing Dependencies

- scripts/mini_RADI/Dockerfile.dependencies_humble
Fixes install versions to avoid deprecation issues in the future
fixes #2166
> Fixed install versions

- scripts/mini_RADI/Dockerfile.mini_humble
moving CustomRobots instead of copying
> Moving CustomRobots instead of copying

- scripts/mini_RADI/Dockerfile.dependencies_humble
- scripts/mini_RADI/Dockerfile.mini_humble
This PR goes along with https://github.com/JdeRobot/RoboticsInfrastructure/pull/328
> [Humble] Setting bash env variable

- exercises/static/exercises/rescue_people_newmanager/python_template/ros2_humble/hal.py
Must be merged with https://github.com/JdeRobot/RoboticsInfrastructure/pull/317
> HAL to use image subscriber node

- exercises/static/exercises/rescue_people_newmanager/haarcascade_frontalface_default.xml
> Added haarcascade xml file

- scripts/mini_RADI/Dockerfile.dependencies_humble
> Updated PX4 and solves drone losing control issue

- react_frontend/src/components/DrawerAppBar.js
> forum link will open in new tab

- README.md
- docs/exercise-status.md
> Exercise status table

- scripts/mini_RADI/build.sh
> added exit if base RADI build fails

- docker-compose-cpu.yaml
- docker-compose.yaml
- scripts/academy_develop.sh
- scripts/run_academy.sh
Adds docker-compose support both for developers and end users
> Docker compose support

- exercises/static/exercises/position_control_newmanager/python_template/ros1_noetic/exercise.py
> Fixed AttributeError for init_beacons in Position Control
