- exercises/follow_line/README.md
- exercises/follow_line/launch/simple_line_follower_ros.launch
I added a launch file for launching the target world instead of retyping the whole command with the world/launch file path. I also updated the README.md to make it easier to follow and suggested that users add the source commands to their bashrc/profile so they don't repeat it every time . I suggest we add tthe last part in the main readme of the repository.
> Added custom world launch file in follow line exercise (Updated README.md accordingly)

- docs/_pages/exercises/Drones/drone_gymkhana.md
- docs/_pages/installation.md
update "Get FastRTPS and FastCDR" url
https://github.com/eProsima/Fast-RTPS-docs/issues/171
As you can see here, the link has been changed
> Update broken URL in Installation Guide

- exercises/follow_line/web-template/README.md
fixes #606 
Directing native installation users to use CustomRobots f1 model. Thus, there will be no bugs for running follow_line web-template without using docker.
> Instructions added for CustomRobots model

- docs/_pages/exercises/Drones/drone_cat_mouse.md
- docs/_pages/exercises/Drones/drone_gymkhana.md
- docs/_pages/exercises/Drones/drone_hangar.md
- docs/_pages/exercises/Drones/follow_road.md
- docs/_pages/exercises/Drones/follow_turtlebot.md
- docs/_pages/exercises/Drones/labyrinth_escape.md
- docs/_pages/exercises/Drones/position_control.md
- docs/_pages/exercises/Drones/rescue_people.md
- docs/_pages/exercises/Drones/visual_lander.md
In the API instructions' section of drones exercises the parameter name for yaw & yaw_rate is 'az' for all the three drone/HAL.set_cmd_vel/pos/mix() drone control calls, which has not been mentioned in the doc leading to confusion for accessing parameters by name. I had made the necessary changes in .md files in /_pages/exercises/Drones/<exercise_name>.md
> Fix for issue #817 - add the parameter name

- exercises/color_filter/web-template/assets/console.js
- exercises/color_filter/web-template/assets/ws_code.js
- exercises/color_filter/web-template/gui.py
- exercises/follow_line/web-template/README.md
- exercises/follow_line/web-template/exercise.html
1. Made changes to the if statements in Exercise.html as using OR( || ) operation with the same operands in both the cases seems unnecessary and ambiguous.
2. **Updated the launching procedure for Windows** - The documentation in the web site just mentions the websocket_address to be the IP Address through which the container is connected. This is straightforward for Linux, but in the case of Windows, the exercise runs on top of Windows Subsystem for Linux(WSL). This means the IP Address through which the container is connected is that of the vEthernet adapter(WSL).
> Updated launching procedure for Windows and a minor unnecessity in follow_line exercise

- exercises/follow_line/web-template/exercise.py
User functions defined inside sequential part don't have the right scope, they can't access global variables, imports nor other functions (issue-870). This does not happen on functions defined inside the iterative part.
The solution I propose is to duplicate the user function definitions (modifying the code sent) from the sequential part to the iterative part. This partially solves the problem:
- functions defined on sequential part and called on iterative part will work correctly
- functions defined on sequential part and called on sequential part will still have the same scope problems
> Duplicated user function definitions

- exercises/color_filter/web-template/assets/ws_code.js
- exercises/follow_line/web-template/assets/ws_code.js
This pull request is in reference to #876 
Removed `saveCode()` and `loadCode()` functions as they are no longer needed for execution from web template. This is because these functions hand over the save/load procedure to `exercise.py`, which is running on the docker container. Saving and loading from the Docker Image wouldn't make sense as those files would be deleted when a running container is removed.
The `local_functions.js` file is instead used now to save/load code to/from the web template.
> Removed saveCode() and loadCode() functions for exercises running via the web template

- docs/_pages/exercises/AutonomousCars/follow_line.md
- docs/_pages/exercises/AutonomousCars/obstacle_avoidance.md
- docs/_pages/exercises/ComputerVision/3d_reconstruction.md
- docs/_pages/exercises/Drones/drone_cat_mouse.md
- docs/_pages/exercises/MobileRobots/vacuum_cleaner.md
- docs/_pages/exercises/MobileRobots/vacuum_cleaner_loc.md
- exercises/static/exercises/drone_cat_mouse/web-template/RADI-launch
- exercises/static/exercises/drone_cat_mouse/web-template/README.md
- exercises/static/exercises/follow_turtlebot/web-template/RADI-launch
- exercises/static/exercises/follow_turtlebot/web-template/README.md
- scripts/README.md
This is the new standard launch instruction:
docker run -it -p 8000:8000 -p 2303:2303 -p 1905:1905 -p 8765:8765 -p 6080:6080 -p 1108:1108 jderobot/robotics-academy python3.8 manager.py
The only exercise which does not use it is color filter as it needs to also map a webcam device.
> RADI launch standardized

- exercises/static/exercises/follow_line/web-template/user_functions.py
Images sent to display are reshaped if the are only 1 channel in order to avoid errors.
> Reshape 1 channel images to 3 channel when sent to GUI

- scripts/manager.py
Hotfix: reverts the wait statement removal between vnc for console and gzclient.
For future improvements, process ready check should be placed instead of wait.
> Reverted wait between vncs

- scripts/Dockerfile-noetic-3.1
Steps to test-
```bash
./build.sh
docker run -it --rm -p 8000:8000 -p 2303:2303 -p 1905:1905 -p 8765:8765 -p 6080:6080 -p 1108:1108 jderobot/robotics-academy:3.1 ./start-3.1.sh
```
Solves #1045 for RADI 3.1 (noetic branch)
> Updated url and version of VirtualGL in Dockerfile-noetic-3.1

- exercises/static/exercises/follow_line/web-template/assets/controller.js
- exercises/static/exercises/follow_line/web-template/assets/launcher.js
- scripts/manager.py
manager.py controlls stop and resume functions. I tried to use similar functions. I only changed `running` variable set from controller.js to launcher.js, as it could create an error (running variable set to false when running, or to true when stopped) if the buttons were clicked two times before the "Ping" message was sent.
> Stop and resume functions controlled by manager

- scripts/Dockerfile
**Existing RADI:-**
```
COPY .env /
COPY manager.py /manager.py
COPY instructions.json /instructions.json
COPY pylint_checker.py /pylint_checker.py
COPY entrypoint.sh /
```
**Updated RADI:-**
`COPY [".env", "manager.py", "instructions.json", "pylint_checker.py", "entrypoint.sh", "./"]`
Only RUN, **COPY** and ADD in Dockerfiles create new layers since version 1.10. Other instructions don’t directly impact the size of the final images. **The current change that combines multiple commands can decrease the number of layers. Fewer layers mean smaller sizes.**
fixes #1680
> Optimised Unnecessary layers in the RADI

- _sass/minimal-mistakes/_base.scss
Google summer of code image was left aligned when viewing from a mobile device. I have centered it to look better.
> centered an image in mobile view

- scripts/Dockerfile
- scripts/Makefile
- scripts/build.sh
This recipe may easy the docker usage for newcomers. Help message is self-explained:
```bash
$ make help
-- Help Menu
help                           Print help info
build                          Build RADI
build-base                     Build RADI base
build-all                      Build RADI and base
test                           Run last built RADI
run                            Run RADI
pull                           Pull latest RADI
prune                          Prune all images
clean                          Remove RADI image
release                        Build and publish the `{version}` and `latest` tagged containers to dockerhub
publish                        Publish the `{version}` and `latest` tagged containers to dockerhub
tag                            Generate container …
```
> Makefile fixed

- docs/gpu_acceleration.md
- exercises/static/exercises/drone_cat_mouse/web-template/launch/launch.py
- exercises/static/exercises/drone_gymkhana/web-template/launch/launch.py
- exercises/static/exercises/drone_hangar/web-template/launch/launch.py
- exercises/static/exercises/follow_road/web-template/launch/launch.py
- exercises/static/exercises/follow_turtlebot/web-template/launch/launch.py
- exercises/static/exercises/labyrinth_escape/web-template/launch/launch.py
- exercises/static/exercises/package_delivery/web-template/launch/launch.py
- exercises/static/exercises/position_control/web-template/launch/launch.py
- exercises/static/exercises/power_tower_inspection/web-template/launch/launch.py
- exercises/static/exercises/power_tower_inspection_react/web-template/launch/launch.py
- exercises/static/exercises/rescue_people/web-template/launch/launch.py
- exercises/static/exercises/rescue_people_react/web-template/launch/launch.py
- exercises/static/exercises/visual_lander/web-template/launch/launch.py
- scripts/manager.py
As of now, DRI device address is hardcoded (`/dev/dri/card0`), and so users can't choose which GPU to use for acceleration.
In this PR, we include changes to allow users to set the environment variable `DRI_NAME` when running the Docker container. If a user has an integrated Intel GPU and a dedicated NVIDIA one, the user can set this new env variable accordingly and choose which GPU to use. Further instructions are provided in [gpu_acceleration.md](https://github.com/JdeRobot/RoboticsAcademy/blob/b24f67208427f05787c5db3dc7f6ee257e3b25f1/docs/gpu_acceleration.md).
Solves issue #1948
> Make DRI device configurable to enable GPU acceleration 

- _pages/exercises/AutonomousCars/autoparking.md
- _pages/exercises/AutonomousCars/car-junction.md
- _pages/exercises/AutonomousCars/follow_line.md
- _pages/exercises/AutonomousCars/global_navigation.md
- _pages/exercises/AutonomousCars/obstacle_avoidance.md
- _pages/exercises/ComputerVision/3d_reconstruction.md
- _pages/exercises/ComputerVision/montecarlo_visual_loc.md
- _pages/exercises/Drones/drone_cat_mouse.md
- _pages/exercises/Drones/drone_gymkhana.md
- _pages/exercises/Drones/drone_hangar.md
- _pages/exercises/Drones/follow_road.md
- _pages/exercises/Drones/follow_turtlebot.md
- _pages/exercises/Drones/labyrinth_escape.md
- _pages/exercises/Drones/package_delivery.md
- _pages/exercises/Drones/position_control.md
- _pages/exercises/Drones/power_tower_inspection.md
- _pages/exercises/Drones/rescue_people.md
- _pages/exercises/Drones/visual_lander.md
- _pages/exercises/MobileRobots/laser_mapping.md
- _pages/exercises/MobileRobots/vacuum_cleaner.md
- _pages/exercises/MobileRobots/vacuum_cleaner_loc.md
- _pages/gpu_acceleration.md
- _pages/installation.md
#1963 Unified RADI install and launching instructions for all exercises except the ones that require a camera parameter to launch.
[Color Filter](https://jderobot.github.io/RoboticsAcademy/exercises/ComputerVision/color_filter),
[Human Detection](https://jderobot.github.io/RoboticsAcademy/exercises/ComputerVision/human_detection)
[Digit Classifier](https://jderobot.github.io/RoboticsAcademy/exercises/ComputerVision/dl_digit_classifier)
[Optical Flow Teleop](https://jderobot.github.io/RoboticsAcademy/exercises/ComputerVision/opticalflow_teleop)
I am unable to launch these exercises correctly #1973 . Hence refrained from updating their docs yet.
A few exercises like [vacuum cleaner](https://jderobot.github.io/RoboticsAcademy/exercises/MobileRobots/vacuum_cleaner) required cloning the git …
> Restructured install and launch docs

- docs/InstructionsForDevelopers.md
- Removed 8080 here because point 5) runs django webserver which already opens 8080, trying to open it again in docker would cause this error :
- Added port 7163 for new RAM
@jmplaza @pariaspe
> updated docker ports

- exercises/templates/exercises/RoboticsAcademy.html
This issue was leading to broken forum link as mentioned in #2027.
**Solution**
The solution was quite simple located the old href="https://forum.jderobot.org/c/english/roboticsacademy/12" and replaced it with new href="https://forum.unibotics.org/" which should fix it.
Let me know if you have any reviews or changes.
> #2027 fixed.

- CONTRIBUTING.md
Some links were redirecting to a 404 page which could be confusing for a new user as mentioned in #2025 .
Easy fix was to change some links in contributing.md so that they land on a page and don't show 404 error.
> #2025 fixed.

- scripts/mini_RADI/Dockerfile.dependencies_humble
https://github.com/JdeRobot/RoboticsInfrastructure/issues/280
Helps reduce base (dependencies_humble) size from 6.8 GBs to 5.3 GBs
Here's the list of changes made:
- Made code styling uniform, easier to read and extend
- Removed packages like alsa-utils alsa-oss lxde-common (not needed)
- Removed ros-humble-desktop, instead use ros-humble-ros-base (decreases the size)
- Clubbed apt installs together to reduce the number of layers and decrease the size
- Restructured Python dependency list and put it at the bottom, since these are likely to have additions in the future, having them at the bottom will help to use the docker cache for system dependencies more effectively.
- Removed duplicate pip installs
> Humble base RADI refactoring 

- scripts/mini_RADI/Dockerfile.dependencies_humble
Solves #2118 
The keyring leads to conflicts between Gazebo classic and Gazebo garden as an install candidate.
> removed keyring for gazebo (not needed)

- scripts/mini_RADI/Dockerfile.mini_humble
If drone_ws isn't sourced, then rosdep starts looking for aerostack packages in apt.
> rosdep install fix

- scripts/mini_RADI/Dockerfile.dependencies_humble
#2227 
Removes gstreamer, pymavlink and pyserial
removing libgstreamer-plugins-base1.0-dev causes px4 build to fail
> Removed unused PX4 dependencies

- docs/InstructionsForDevelopers.md
Fixes #2315 
By default runserver runs on port 8000 and we have migrated to port 7164.
> Fixed pylint version and fixed runserver command

- docs/requirements.txt
I was getting error while adding exercise which I discussed in [2471](https://github.com/JdeRobot/RoboticsAcademy/issues/2471). I have added pylint==2.17.4 in requirements.txt which solves the error while running python3 manage.py.
> Error in adding exercise.
